### PR TITLE
Reduce height of app and clean up styling

### PR DESCRIPTION
**Pull request by schiguoi**
I adjusted the initial loading page to be much shorter to reduce the amount of space taken when the app is loaded and also adjusted some styling.

### CODE REVIEW

**Comment by schiguoi** [comment]
Screenshot of updated application with height and style. 
screen shot 2017-05-13 at 7 00 40 pm

**Comment by dpawluk** [comment]
@schiguoi thanks so much for your contribution. I'm sorry I missed it before making my latest merges. Would you mind fixing the conflicts and I can +1 and merge this. Thanks again!

**Comment by schiguoi** [comment]
I resolved the issues.  Thanks for taking a look at this! First time really using (and contributing) GitHub and Zendesk Apps so it's great adding value.

**Comment by schiguoi** [comment]
@dpawluk Thanks for reviewing and approving this.  Now that I have been invited to collaborate on this,  What is the best way to merge this in?  I'm really new to this git stuff so I don't want to do something that will break  this repository or anything.  Is it okay for me to go ahead and squash and merge this request or is that something I should wait for you to do?

**Comment by dpawluk** [comment]
Totally cool for you to merge and delete the branch. The nice thing about git is we can always revert. Thanks again!

**Pull request merged**
